# -*- coding: utf-8 -*-
"""Copy of Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pG-EZV7dGnjBjwava2urdgqwkzOEhdp0
"""

a = 5
b = 5
print(id(a) == id(b))

x =5
print(id(a))

x = 8
print(id(x))

print(x is x)

d =9
print(d is d)

def func(a,b):
  if a == 1:
    return b
  else:
    return func(a-1,a*b)
print(func(4,2))

phone_book = {}

name = input("Enter the name: ")
phone = input("Enter the phone number: ")
phone_book[name] = phone

print("Phone Book:")
for key, value in phone_book.items():
    print(f"{key}: {value}")

import pandas as pd

# Create a DataFrame
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}
df = pd.DataFrame(data)

# Display the DataFrame
print("Original DataFrame:")
print(df)

age = 20

if age >= 18:
  print("You are an adult.")
else:
  print("You are a minor.")

import pandas as pd
lst1=[]
lst2 = []
for i in range(6):
  name = input("Enter the name :")
  lst1.append(name)
  age = int(input("Enter the age :"))
  lst2.append(age)
data1 = {'Name':lst1,'Age':lst2}

df = pd.DataFrame(data=data1)
print(df)
exels=df.to_excel('data.xlsx')

exels=df.to_excel('data.xlsx')

CGPA=[]
for i in range(6):
  cgpa = float(input("Enter the cgpa :"))
  CGPA.append(cgpa)
  print(CGPA)
df['CGPA']=CGPA
print(df)
exels=df.to_excel('data.xlsx')

Dept=[]
for i in range(6):
  dept = input("Enter the department :")
  Dept.append(dept)
  print(Dept)
df['Department']=Dept
print(df)
exels=df.to_excel('data.xlsx')

a=3
b=4
a=a^b
b=a^b
a=a^b
print(a,b)

"""# New Section"""

import pandas as pd

df=pd.read_csv('iris.csv')
print(df)

arr=[2,3,55,6,88,9]
max=arr[0]
for i in range(1, len(arr)):
  if arr[i] > max:
    max=arr[i]
print(max)



"""# New Section"""



names = ["Alice", "Bob", "Charlie"]

for name in names:
  print(name)

txt = "Hello World"
print(txt[:5])  # Output: "Hello"
txt = "Hello World"
print(txt[2:])  # Output: "llo World"

import pandas as pd

# Create a DataFrame (as you provided)
data = {
    'Name': ['Alice', 'Bob', 'Charlie'],
    'Age': [25, 30, 35],
    'City': ['New York', 'Los Angeles', 'Chicago']
}
df = pd.DataFrame(data)

# Convert the DataFrame to a CSV file
df.to_csv('data.csv', index=False)

num=list(range(10))
print(num)

num=tuple(range(10))
print(num)



num=tuple(range(10))
print(num[1:4])

for num in range(10):
  print(num)

num = [1,2,3,4,5,6]
num1 = (66,77,88,99)
print(num.insert(2,num1))

for i in range(1,5):
  print("*" * i)

for i in range(1,5):
  print(" "*(5-i)+i * "*")

for i in range(6,0,-1):
  print("*" * i)

for i in range(6,0,-1):
  print((6-i) * "*")

str2 = str(input("Enter a string :" ))
str3 =tuple(str2.split())
print(str3)

str1 = str(input("Enter string :"))
print(str1.split(" "))

num = 0
latter = 0
word = 0
x = input("Enter the input :")
for i in x:
  if i >= 'a' and i <= 'z' :
    latter = latter +1
  elif i >= '0' and i <= '9' :
    num = num +1
  elif i == ' ' :
    word = word +1
print(latter)
print(num)
print(word)

matrix = [[1,2,3],[4,5,6]]
for row in matrix:
  for col in row:
    print(col)

from collections import deque
bank = deque(["shakib", "islam", "saiful"])

f= bank.popleft()

print(f)



from collections import deque
bank = deque(["shakib", "islam", "saiful"])

f= bank.popleft()

print(f)

from collections import deque
bank = deque(["shaown", "babo", "shafik","shakib", "islam", "saiful"])

bank.popleft()
bank.popleft()
print(bank)

list1 = [33,44,66,77,88,99,100]
del list1[2]
print(list1)

from collections import deque
bank = deque(["shakib", "islam", "saiful"])
for i in range(len(bank)):
   bank.popleft()
print(bank)

def add(x,y):
  sum = x + y
  print(sum)
for i in range(10):
  add(10,i)

def add(x,y):
  sum = x + y
  print(sum)
add(10,20)
add(10,30)
add(10,40)

list1= ["banana", "apple", "mango", "orange"]
[print(x) for x in list1]

list1= ["banana", "apple", "mango", "orange"]
list2 = []
for x in list1:
  if 'n' in x:
    list2.append(x)
print(list2)



"""# New Section"""

list1= ["banana", "apple", "mango", "orange"]
list2 = [x for x in list1 if 'e' in x]
print(list2)

print([x for x in range(10)])

list1= ["banana", "apple", "mango", "orange"]
list2 = [x.upper() for x in list1]
print(list2)

list1= ["banana", "apple", "mango", "orange"]
list2 = [x.casefold() for x in list1]
print(list2)

list1= ["banana", "apple", "mango", "orange"]
list2 = [x.upper() for x in list1]
print(list2)



"""xxargoments and xxxargoments

"""

list1 = ["shakib", "saiful", "islam", "shaown", "babo"]
for x in list1:
  print(x)

list1 = ["shakib", "saiful", "islam", "shaown", "babo"]
#for x in list1
[print(x) for x in list1]

"""x-argumens"""

def std(*details):
  print(details)
std(101, "shakib", 3.11)

"""lamda function"""

def calculate(a,b):
    return  a*a + 2*a*b + b*b
print(calculate(2,3))

print((lambda a,b: a*a + 2*a*b + b*b)(2,3))

"""map and filter function"""

def square(x):
  return x*x
num = {1,2,3,4,5,6}

result = list(map(square,num))
print(result)

num = {1,2,3,4,5,6}
print(list(map(lambda x : x*x, num)))

num = {1,2,3,4,5,6,7,8,9}
result = list(filter(lambda x : x % 2 != 0, num))
print(result)

"""list comprehension"""

num = [1,2,3,4,5,6,7]
result = [x*x for x in num]
print(result)

list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
list1.extend(list2)
print(list1)

list1 = [1,2,3,4,5,6]
for i in list1:
  print(i)

list1 = [1,2,3,4,5,6]
for i in range(len(list1)):
  print(i)

fruit = ["apple", "roange", "cherry", "mango"]
newlist = []
for x in fruit:
  if "a" in x:
    newlist.append(x)
print(newlist)

fruit = ["apple", "roange", "cherry", "mango", "painappple", "lele"]

newlist = [x for x in fruit if "a" in x]
print(newlist)

print([x for x in range(10)])

fruit = ["apple", "roange", "cherry", "mango", "painappple", "Banana"]
fruit.sort()
print(fruit)

fruit = ["apple", "roange", "cherry", "mango", "painappple", "lele"]
fruit.sort(reverse= True)
print(fruit)

def func(n):
  return abs(n-50)

list1 = [30,40,50,12,24,44]
list1.sort(key=func)
print(list1)

num = [1,2,3,4,5,6]
result = list(map(lambda x:x*x, num))
print(result)

num = [1,2,3,4,5,6]
result = [x*x for x in num]
print(result)

"""zip function"""

num = [1,2,3,4,5,6]
name = ["shakib", "saiful", "babo", "shaown","islam","shafiq"]
print(list(zip(num,name)))

thisdict =	{
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964,
  "name": "shakib",
  "name1": "islam"
}
print(thisdict)

class student():


   def __init__(self,name,id):
    self.name=name
    self.id=id

   def details(self):
    print("name:",self.name,"id:",self.id)

s1 =  student("shakib,", 416)
s2 =  student("hasin,", 383)
s1.id=222

s1.details()
s2.details()

x =int(input("numnber1 :"))
y =int(input("numnber1 :"))
print(x,y)

x =x+y
y=x-y
x=x-y
print(x,y)

print(2**3 + (5 + 6)**(1 + 1))

print(2**3 + (5 + 6)**(1 + 1))
2**3
11**2

a = [1,2,3,4,5,6]
for a[-1] in a:
  print(a[-1])
#print(a)

#AREA OF CIRCLE

import math
pi = math.pi

r = int(input('Enter the radius :'))
print(pi*r**2)

# AREA OF REACTANGULAR

import math
r1 = int(input('Enter the border1 :'))
r2 = int(input('Enter the border2 :'))

print(r1 * r2)

name = input('Enter your name : ')
age = int(input("Enter youor age :"))

print(f"Hi {name}! Your age is {age}")

name = input("Enter name :")
age = int(input("Enter the age :"))

if age >= 18:
  print(f"Hi {name} you can take perticipate!")
else:
  y=18 - age
  x = y + age
  print(f"sorry!{name} can't perticipate. You perticipate afer {y} year letter. When your age is {x}")

a = int(input("Enter the number for A :"))
b = int(input("Enter the number for B :"))
c = int(input("Enter the number for C :"))

print("Adition ", a+b+c)
print("subtraction ", a+b+c)
print("multiplication", a+b+c)
print("division ", a/(b+c))
print("Modulous ", a%(b+c))

a = {1,2,3,4,7,8}
b = {9,8,7,6,11,12,5}
#addition
print(a | b)
#subtraction
print(a - b)
#addition
c =a.union(b)
print(c)

a = {1,2,3,4,7,8}
b = {9,8,7,6,11,12,5}
c = {99,88,77,66,1,2,55}

#addition
print(a | b | c)

#subtraction
print(a - c - b)

#addition
d =a.union(b,c)

print(d)

num1 = int(input("Enter the number : "))
num2 = int(input("Enter the number : "))

print("The table of this number ")

for i in range(1,11):
  print(i, " * ", num1 ," = ", i*num1)

for i in range(1,11):
  print(i, " * ", num2 ," = ", i*num2)

num2 = {66,77,88,99,65,68}


sum =0
for i in num2:
  sum = sum + i

print("sum is =",sum)
print("average is =",sum/6)

a = int(input("Enter the number : "))
b = int(input("Enter the number : "))
c = int(input("Enter the number : "))

if a>b and a>c:
  print(f"{a} is greater than {b} and {c}")
elif b>c:
  print(f"{b} is greater then {a} and {c}")
else:
  print(f"{c} is greater then {a} and {b}")

for i in range(6):
  print("*"*i)

for i in range(6):
  print(" "*(5-i)+"*"*i)

for i in range(6,0,-1):
  print("*"*i)

for i in range(6,0,-1):
  print(" "*(6-i)+"*"*i)

pwd = input("Enter your password")

if pwd.isalnum():
  print("Pwd contain alpha or numeric")
else:
  print("Not")

pwd = input("Enter your password : ")

if (pwd.isalnum() and len(pwd) <= 8):
  print("Pwd contain alpha or numeric and length is not greater then 8")
else:
  print("Not")

s = 0
lst = []
for i in range(6):
  lst.append(int(input("Enter the number : ")))

print("The list is",lst)

for j in lst:
  s = s + j
print("Sum of this lis number",s)

lst = []
for i in range(6):
  lst.append(int(input("Enter the number : ")))

print("The list is",lst)
print(lst.clear())

lst = []
for i in range(6):
  lst.append(int(input("Enter the number : ")))
print("The list is",lst)

tup = tuple(lst)
print("The tuple is",tup)
#delete tuple

del tup
tup = tuple(lst)

print(tup)

num1 = 0
num = int(input("Enter the nuimber :"))
num += 5
print(num)

num1 += num

num  = num - 5
print(num)

num1 += num

num *= 5
print(num)

num1 += num

num /= 5
print(num)

num1 += num

num %= 5
print(num)

num1 += num
print("sum = ", int(num1))

print("A")
print("A\tB")
print("A\tB\tC")
print("A\tB\tC\tD")
print("A\tB\tC")
print("A\tB")
print("A")

for i in range(7,0,-1):
 # for j in range(i):

   print(chr(65 + i)*i)

  #print('\n')

for i in range(7):
  for j in range(i + 1):
    print(chr(65 + i)*j)

  #print('\n')

for i in range(7):
  print(chr(64 + i)*i)
print("\n")

dict1 = {
    "name": "shakib",
    "address": "chittagong",
    "mobile": 182476783,
     "age": 23



}
print(dict1)
dict1["university"] = "PCIU"
print(dict1)
dict1.update({"gender" : "male"})
print(dict1)
print(dict1.keys())
print(dict1.values())

dict1 = {
    "name": "shakib",
    "address": "chittagong",
    "mobile": 182476783,
     "age": 23
}
print(dict1)

num = int(input("Enter the mobile number : "))

dict1["mobile"] = num
#dict1.update({"molbile":num})
print(dict1)

a = int(input('Enter a :'))
b = int(input('Enter b :'))
c = int(input('Enter c :'))
result =  (a + b + c )*(a / b) * ( 2*a + 3*b )
print(result)

a = int(input('Enter a :'))
b = int(input('Enter b :'))
c = int(input('Enter c :'))
d = int(input('Enter d :'))

result =  (d + a + 2*a) * (b/d) * (4*c + 10)
print(result)

s =0
num = []
for i in range(6):
  num.append(int(input("Enter the number :")))

for j in range(len(num)):
    print(num[j])
    s += num[j]
print("sum = ",s)

max = num[0]
num = []
for i in range(6):
  num.append(int(input("Enter the number :")))

for j in range(1,len(num)):
  if max < num[j]:
    max = num[j]
print('maximum number = ',max)

min = num[0]
num = []
for i in range(5):
  num.append(int(input("Enter the number :")))

for j in range(1,len(num)):
  if num[j]< min:
    min = num[j]
print('minimum number = ',min)

a = int(input("Enter number a : "))
b = int(input("Enter number b : "))
c = input("Enter number  c: ")
if (c == '+'):
  print("Adition : ", a +b)
elif (c == '-'):
  print("subtraction : ", a-b)
elif (c == '*'):
  print("multiplication : ", a*b)
elif (c == '/'):
  print("division : ", a/b)
elif (c == '%'):
  print("modulus : ", a%b)
elif c not in '+-*/%':
  print("INvalid oprtator : ", c)

max = 0
leap1 = []
num = []
for i in range(5):
  num.append(int(input("Enter the number :")))

for j in range(1,len(num)):
  if  num[j] % 4 ==0 or num[j] % 400 == 0 or num[j] % 100 == 0 :
    max = num[j]
    leap1.append(max)
print('list of leap year = ',leap1)

max = []
leap1 = []
num = []
for i in range(5):
  num.append(int(input("Enter the number :")))

for j in num:
 leap1.append(j**3)
 max.append(j**2)
print('quve of list number = ',leap1)
print('square of list number = ',max)

num = int(input("Enter the number :"))

if (num % (2 and 3 ) == 0):
  print("Divisible by 2 or 3")
else:
  print("Enter another number")

num = int(input("Enter the number :"))

if (num % (5 and 6 ) == 0):
  print("Divisible by 5 or 6")
else:
  print("Enter another number")

a = int(input("Enter the number :"))
b = int(input("Enter the number :"))
def maximum(x,y):

  print("x = ",x)
  print("y = ", y)
  if x > y:
    print("1) a is greater then b")
  else:
    print("2) b is greater then a")
maximum(a,b)

a = int(input("Enter the number :"))
b = int(input("Enter the number :"))
def maximum(x,y):

  print("a = ",x)
  print("b = ", y)
  if x < y:
    print("1) a is smaller then b")
  else:
    print("2) b is  smaller then a")
maximum(a,b)

lst = []

for i in range(3):
  lst.append(input("Enter the name of color :"))
print(lst)
print(len(lst))

lst = []

for i in range(4):
  lst.append(input("Enter the name of color :"))
print(lst)
print(len(lst))
lst.pop(-1)
print(lst)

lst = []

for i in range(4):
  lst.append(input("Enter the name of color :"))
print(lst)
print(len(lst))
lst.pop(0)
print(lst)

lst = []

for i in range(4):
  lst.append(input("Enter the name of color :"))
#print(lst[::-1])
lst.reverse()
print(lst)

lst = []

for i in range(4):
  lst.append(input("Enter the name of color :"))
#print(lst[::-1])
lst.pop(0)
lst.pop(-1)
lst.reverse()
print(lst)

cher = input("Enter the sentencce :")
print(cher.upper())

lst = []

for i in range(4):
  lst.append(input("Enter the name of color :"))
#print(lst[::-1])
lst.reverse()
print(lst)

import math
deg  = int(input("Enter the degree : "))
red = math.radians(deg)
print("converted to redian : ", red)

s = 0
m =1
lst=[]
for i in range(5):
  lst.append(int(input("Enter the number : ")))
print(lst)

for j in lst:
  s = s + j
  m = m * j
print("adtion = ",s)
print("multiplication = ",m)

user = input("Enter alpanumeric : ")

def check_user(u):
  if (u.isalnum()):
    print("User name is okk")
  else:
    print("Enter a valid user name")
check_user(user)

user = input("Enter alpanumeric : ")

def check_user(u):
  if (u.isalnum()):
    print("User name is okk")
  else:
    print("Enter a valid user name")
if len(user) <= 8:
   print("Programm pass your user name")
   check_user(user)
else:
  print("Enert user name which len is less or equal to 8")

import math
angle = float(input("Enter the angle : "))

sin_value = math.sin(angle)

cos_value = math.cos(angle)
print("sin_value = ", sin_value)
print("cos_value = ", cos_value)

print("number\t\tsquare\t\tqube\t\taddtition")

for i in range(10,0,-4):

    print(str(i),"\t\t"+str((i**2)),"\t\t",str((i**3)),"\t\t",str((i**2)+(i**3)))

print("number\t\tsquare\t\tqube\t\taddtition")

for i in range(0,10,3):

    print(str(i),"\t\t"+str((i**2)),"\t\t",str((i**3)),"\t\t",str((i**2)+(i**3)))

e = int(input("Enter the ending number : "))
s = int(input("Enter the starting number : "))

for i in range(e, s-1, -1):
  print(i)

sum = 0

e = int(input("Enter the ending number : "))
s = int(input("Enter the starting number : "))

for i in range(e, s-1, -1):
  sum = sum + i
  print(i)
print("sum = ", sum)

s = int(input("Enter the starting number : "))
e = int(input("Enter the ending number : "))
for i in range(s, e,3):
    if i % 2 != 0:
      print(i)

s = int(input("Enter the starting number : "))
e = int(input("Enter the ending number : "))

print((s**2)+ (e**2))

import math
s = int(input("Enter the starting number : "))
e = int(input("Enter the ending number : "))

print((math.pow(s,3))+ (math.pow(e,3)))

s = int(input("Enter the starting number s: "))
e = int(input("Enter the ending number e: "))
x = s + e
s = x - s
e = x - s
print("balue = ",s," balue = ",e)

s = int(input("Enter the starting number s: "))
e = int(input("Enter the ending number e: "))

t = s
s = e
e = t
print(s,e)

a = 5
b = 6

a , b = b , a

print(a,b)

h = int(input("Enter the height : "))
b = int(input("Enter the base : "))
area = (h * b)/2
print("Area = ", area)

s = int(input("Enter the starting number s: "))
result = (s ** 2) + area

print("Reasult = ", result)

from datetime import datetime

date1 = input("Enter the first_date: ")
date2 = input("Enter the second_date: ")
date_formate = "%m/%d/%Y"

d1 = datetime.strptime(date1, date_formate)
d2 = datetime.strptime(date2, date_formate)

result = d2 - d1

print(result)

from datetime import datetime

date1 = input("Enter the first_date: ")
date2 = input("Enter the second_date: ")
date_formate = "%m/%d/%Y"

d1 = datetime.strptime(date1, date_formate)
d2 = datetime.strptime(date2, date_formate)

result = abs((d2 - d1).total_seconds()/3600)

print(result, "Hours")

st = input("Enter a string for reversing : ")
reverse_st = " "
for i in st:
  reverse_st = i + reverse_st
print(reverse_st)

st = input("Enter a string for reversing : ")
reverse_st = " "
for i in st:
  reverse_st = i + reverse_st
print('"',reverse_st+'."')

from datetime import datetime

age = int(input("Enter the Age : "))


result = age * 24 * 3600
print(result,'sec')

import math

num = int(input("Enter the number : "))

fact_of_num = math.factorial(num)
print(f"factorial of {num} is {fact_of_num}")

num = 1

a = int(input("Enter the number : "))
for i in range(1, a + 1):
  num =num * i
print(f"facorial of {a} is {num}")

from datetime import datetime

usr = input("Enter the yes or not : ")

if (usr == ('yes' or 'Yes' or 'YES')):
  current_date = datetime.now()
  print(current_date.strftime("%Y-%m-%d"))
else:
  print("Not show current datetime")

from datetime import datetime

usr = input("Enter the yes or not : ")

if (usr == ('yes' or 'Yes' or 'YES')):
   print(datetime.now())

else:
  print("Not show current datetime")

from datetime import datetime

usr = input("Enter the yes or not : ")

if (usr == ('yes' or 'Yes' or 'YES')):

  value = datetime.now()
  second = (value - datetime(1970,1,1)).total_seconds()
  milisecond = second * 1000
  print(round(milisecond))



else:
  print("Not show current datetime")

decimal_number = int(input("Enter the decimal number : "))
binary_number = bin(decimal_number)
print(binary_number)

sum = 0
a = int(input("Enter the terminator : "))
b = []
for i in range(a):
  b.append(int(input("Enter the number : ")))
print(b)
for j in b:
  sum = sum + j
print("Average is = ", sum / a)

binary_number = input("Enter the binary number : ")
decimal_number = int(binary_number,2)
print(decimal_number)

gb = int(input("Enter the  size of gigabyte : "))

byt = gb * 1024 * 1024 * 1024

#bytes(gb)

print(byt)

byt = float(input("Enter the  size of gigabyte : "))

gb =( 2 *  byt) /(1024 * 1024 * 1024)

#bytes(gb)

print(gb,'GB')

lst = []

for i in range(5):
  lst.append(int(input("Enter the number : ")))
print(lst)

def max_num(max1):
    print("maximum number on the list : ", max(max1))
max_num(lst)

lst = []

for i in range(5):
  lst.append(int(input("Enter the number : ")))
print(lst)

def min_num(min1):
   print("minimum number on this list :  ", min(min1))
min_num(lst)

lst = []

for i in range(5):
  lst.append(int(input("Enter the number : ")))
print(lst)

def min_num(p):

    list2 = p[::-1]
    print(list2)

min_num(lst)

lst = []

for i in range(5):
  lst.append(int(input("Enter the number : ")))
print(lst)

def min_num(p):

    p.reverse()
    print(p)

min_num(lst)

lst = []

for i in range(5):
  lst.append(input("Enter the number : "))
print(lst)

def min_num(p):

    p.reverse()
    print(p)

min_num(lst)

num = int(input("Enter the number : "))
for i in range(2,num):
  if (num % i == 0):
    print("not a prime number ")
    break
else:
  print("prime number")

lst = []

for i in range(5):
  lst.append(input("Enter the number : "))
print(lst)
lst.clear()
print(lst)

if (len(lst) == 0):
    print("list is empty", lst)
else:
  print("not empty")

file = open("file1.txt","w+")
name = input("Enter your name : ")
age = int(input("Enter your age : "))

file.write("your name is " +str(name))
file.write("your age is " +str(age))
file.seek(0)
R = file.read()

print(R)

file.close()
#!cat file1.txt

file = open("file1.txt","w+")
num1 = int(input("Enter your name : "))
num2 = int(input("Enter your age : "))

num = num1 + num2
file.write("sum of two number ", str(num) )
file.seek(0)
R = file.read()

print(R)

file.close()
#!cat file1.txt















test = input("Enter the character ")
if test in "aeiouAEIOU":
  print("vowewl")

elif test.isdigit():
 print("number", test)
else:
 print("consonent")







class student:

  def __init__(self,Nm,I):
    print("An object is created")
    self.name = Nm
    self.id = I


s1 = student("shakib",1)
s2 = student("saiful",2)
print(s1.name)
print(s2.name)

class House:

  def __init__(self):
    self.windo =4
    self.door =2

  def view(self):
    print(self.windo,"window", self.door, "door")


h1 = House()
h2 = House()
h1.view()
h2.view()

class  Car:

  def __init__(self, name,  model):
    self.name = name
    self.model_year = model
    self.wheel = 4

  def view(self):
    print("my car is ", self.name, "model is", self.model_year)
    print("The car is ", self.wheel, "wheel")

c1 = Car("BMW", 2018)
c2 = Car("Audi", 2019)
c2.wheel = 7
c1.view()
c2.view()

class dog:

  def __init__(self, name , color):
     self.name = name
     self.color = color

  def update_color(self, color):
    self.color = color

  def poke(self):
    print(self.color, self.name, "is very big")

d1 = dog("bunky", "green")
d2 = dog("dunky", "white")

d1.poke()
d1.update_color("black")
d1.poke()
d2.poke()
d2.update_color("yellow")
d2.poke()
print(d1.__dict__)
print(dir(d1))

class book:

  def __init__(self, name , author):
     self.name = name
     self.author = author
     self.price = 0

  def set_price(self, price):
    self.price = price

  def get_price(self):
      return self.price

  def details(self):
        print("book name", self.name, "\nauthor ", self.author, "\nprice = ", self.price)

# b1 = book("opekka", "humayon")
# b1.details()
# b1.set_price(222)
# b1.details()
# print(b1.get_price())

!pip show book
b1 = book("opekka", "humayon")
b1.details()
b1.set_price(999)
b1.details()
print(b1.get_price())
print("------------------")
b2 = book("onorodhe", "shakib")
b2.details()
b2.set_price(1000)
b2.details()
print(b2.get_price())

class cat:

  def __init__(self, name, action):
    self.name = name
    self.action = action

  def view(self):
    print(self.name , " is ", self.action)

  def compare(self, ct):
    if self.action == ct. action:
      print("Both are ", ct.action)
    else:
      print("They are not same")

c1 = cat("DON", "SLIPPPING")
c2 = cat("DUK", "SLIPPPING")
c1.view()
c2.view()

c1.compare(c2)

class cat:

  def __init__(self, name, action):
    self.name = name
    self.action = action

  def view(self, num, clr):
    num = num + 5
    clr1 = clr
    clr1[0] = 'Green'

    print("Inside ", num)
    print("Inside ", clr1)

colors = ['Black', 'Red', 'Yellow', 'Blue']
c1 = cat("white", "jumping")

x =55
c1.view(x, colors)
print("outide ", x)
print("outside ", colors)

from multipledispatch import dispatch
class my_calcolator:

      @dispatch(int,int)
      def product(self, a,b):
        print(a*b)

      @dispatch(int,int,int)
      def product(self, a,b,c):
        print(a*b*c)


p1 = my_calcolator()
p1.product(2,3)
p1.product(2,3,2)

class student:

  def __init__(self, name, Id):
    self.name=name
    self.id=Id
  print(self.name, self.Id)

s1 = student("carol",99)

class MyNumbers:
  def __iter__(self):
    self.a = 1
    return self

  def __next__(self):
    x = self.a
    self.a += 1
    return x

myclass = MyNumbers()
myiter = iter(myclass)

print(next(myiter))
print(next(myiter))
print(next(myiter))
print(next(myiter))
print(next(myiter))

list1 = [1,2,3,4,5,6,7]
print(list1[::-1])

import datetime

x = datetime.datetime.now()

print(x)

!pip install camelcase
import camelcase


c = camelcase.CamelCase()

txt = "hello world"

print(c.hump(txt))

import random

print("Welcome to Hangman!")

words = ["hacker", "bounty", "random"]
secret_word = random.choice(words)
print("You get 5 guesses")
display_word = []
for letter in secret_word:
    display_word += "_"
print(display_word)

num = 0
game_over = False

while not game_over:
    guess = input("Guess a letter ").lower()
    for position in range(len(secret_word)):
        letter = secret_word[position]
        if letter == guess:
            display_word[position] = letter
    if guess not in secret_word:
        num += 1
        guesses_left = 5 - num
        print(f"You have {guesses_left} guesses left")
        if num >= 5:
            print("You Loser")
            game_over = True
    print(display_word)

    if "_" not in display_word:
        print("You Win")
        game_over = True

for i in range(1,50):
   if i % 3 ==0:
    print("fizz")
   elif i % 5 ==0:
     print("buzz")
   elif i % 3 and i % 5==0:
     print("fizz-buzz")
   else:
    print(i)

import requests
import sys

res = requests.get(url=f"http://10.10.11.161/api")

print(res)

print("shakib")

for i in range(5):
  print(i*4)

print("shakib")





